version: "3.0"

services:

  redis:
    container_name: redis
    restart: always
    build:
      context: ./dockerfiles/redis/
      dockerfile: Dockerfile
    ports:
      - "6499:6379"

  mariadb:
    container_name: mariadb
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/dockerfiles/mysql/Dockerfile
    volumes:
      - ../mysqldata:/var/lib/mysql
    ports:
      - "14006:3306"


  web_backend:
    container_name: animation
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/dockerfiles/web_backend/Dockerfile
    volumes:
    - ..:/app
    ports:
      - "6500:5000"