version: "3.0"

networks:
  animation:
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/24"
          gateway: 172.22.0.1

services:

  redis:
    container_name: redis
    restart: always
    build:
      context: ./dockerfiles/redis/
      dockerfile: Dockerfile
    ports:
      - "6499:6379"
    networks:
      animation:
        ipv4_address: 172.22.0.2

  mariadb:
    container_name: mariadb
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/dockerfiles/mysql/Dockerfile
    volumes:
      - ../mysqldata:/var/lib/mysql
    ports:
      - "14006:3306"
    networks:
      animation:
        ipv4_address: 172.22.0.3


  web_backend:
    container_name: animation
    restart: always
    build:
      context: ..
      dockerfile: ./deployment/dockerfiles/web_backend/Dockerfile
    volumes:
    - ..:/app
    ports:
      - "6500:6500"
    networks:
      animation:
        ipv4_address: 172.22.0.4