mysql:
  host: 127.0.0.1
  port: 14006
  user: root
  password: sadnesspineapple
  db: animation
  autocommit: true

redis:
  host: 127.0.0.1
  port: 6499
  password: sadnesspineapple


jwt:
  key: d41d8cd98f00b204e9800998ecf8427e
  ex: 15

minio:
  protocol: http
  endpoint: oss.qunqing.cc:9001
  access_key: ANIMATION
  secret_key: Animation-114514