SUCCESS = {"code": 200, "message": "success"}
ERR_SYSTEM_BUSY = {"code": 5000, "message": "please try later"}
ERR_PARAM = {"code": 5001, "message": "param error"}
USER_NOT_FOUND = {"code": 5002, "message": "user not found"}
ERR_PASSWORD = {"code": 5003, "message": "error password"}
USER_EXISTS = {"code": 5004, "message": "user exists"}
USER_NO_LOGIN = {"code": 5005, "message": "user need login"}
TOKEN_EXPIRED = {"code": 5006, "message": "token expired"}
AUTHOR_NOT_FOUND = {"code": 5007, "message": "author not found"}
